services:
  mysql:
    container_name: db_ms_library
    image: mysql:8.0.39
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 6033:3306
    volumes:
      - library_volume:/var/lib/mysql
      - ./_database/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - ms_library_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  pma:
    container_name: admin_ms_library
    image: phpmyadmin:latest
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 3030:80
    environment:
      - PMA_HOST=db_ms_library
    networks:
      - ms_library_network

  ms_quarkus_author:
    container_name: author-service
    build: ./author-service
    restart: always
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://db_ms_library/ms_library_author
#      - QUARKUS_HTTP_PORT=8080
      - BOOK_SERVICE_MP_REST_URL=http://book-service:8081
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=validate
#      - QUARKUS_HTTP_CORS=false
#      - QUARKUS_HTTP_CORS_ORIGINS=/.*/
#      - QUARKUS_HTTP_CORS_METHODS=GET,POST,PUT,DELETE
    ports:
      - 8082:8082
    networks:
      - ms_library_network

  ms_quarkus_book:
    container_name: book-service
    build: ./book-service
    restart: always
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://db_ms_library/ms_library_book
      - AUTHOR_SERVICE_MP_REST_URL=http://author-service:8082
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=validate
    ports:
      - 8081:8081
    networks:
      - ms_library_network

  ms_quarkus_user:
    container_name: user-service
    build: ./user-service
    restart: always
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://db_ms_library/ms_library_user
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=validate
    ports:
      - 8083:8083
    networks:
      - ms_library_network

  ms_quarkus_borrow:
    container_name: borrow-service
    build: ./borrow-service
    restart: always
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
      ms_quarkus_book:
        condition: service_started
      ms_quarkus_user:
        condition: service_started
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db_ms_library/ms_library_borrow
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: validate
      BOOK_SERVICE_MP_REST_URL: http://book-service:8081
      USER_SERVICE_MP_REST_URL: http://user-service:8083
    ports:
      - 8080:8080
    networks:
      - ms_library_network

  ms_quarkus_review:
    container_name: review-service
    build: ./review-service
    restart: always
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
      ms_quarkus_book:
        condition: service_started
      ms_quarkus_author:
        condition: service_started
      ms_quarkus_user:
        condition: service_started
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db_ms_library/ms_library_review
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: validate
      BOOK_SERVICE_MP_REST_URL: http://book-service:8081
      USER_SERVICE_MP_REST_URL: http://user-service:8083
    ports:
      - 8084:8084
    networks:
      - ms_library_network




volumes:
  library_volume:
networks:
  ms_library_network: