services:
  mysql:
    container_name: db_employee
    image: mysql:8.0.39
    environment:
      - MYSQL_DATABASE=employee
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 6033:3306
    volumes:
      - v_db_employee:/var/lib/mysql
    networks:
      - ex2network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    ports:
      - 3030:80
    environment:
      - PMA_HOST=db_employee
    networks:
      - ex2network
    
  back_spring:
    depends_on:
      - mysql
    restart: always
    container_name: spring_app
    build: 
      context: ./back_employee
      dockerfile: dockerfile
    ports:
      - 8080:8080
    command: --spring.datasource.url=jdbc:mysql://db_employee/employee
    networks:
      - ex2network

  front_react:
    depends_on:
      - back_spring
    container_name: react_app
    restart: always
    build: 
      context: ./front_employee
      dockerfile: dockerfile
    ports:
      - 80:80
    networks:
      - ex2network

volumes:
  v_db_employee:
networks:
  ex2network: