FROM node

WORKDIR /usr/src/app
COPY package*.json .
RUN npm install
COPY . .

EXPOSE 3001
CMD ["node", "app"]

# docker build --no-cache -t node-api .
# docker run -dp 8081:3001 --name api-container node-api