FROM nginx
LABEL version="0.1a" author="francoisdoue"
WORKDIR /usr/share/nginx/html
RUN apt update -y && apt upgrade -y && apt install git -y
RUN git clone https://github.com/withaarzoo/3D-Rotate-Tube
RUN mv 3D-Rotate-Tube/* . && rm -r 3D-Rotate-Tube
EXPOSE 80
CMD ["nginx", "-g","daemon off;"]

# docker build --no-cache -t nginx-rotate-tube .
# docker run --name rotate -dp 8080:80 nginx-rotate-tube