services:
  db:
    container_name: drp_postgresql
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=drupal
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - drupal_network
  
  drupal:
    image: drupal:10-apache
    container_name: drp_drupal
    links: 
      - db
    ports: 
      - 8080:80
    volumes: 
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
    networks:
      - drupal_network

volumes:
  pg_volume:
networks:
  drupal_network: